### ISSUE TITLE
Gitlab: Could not authenticate you from Redmine because "401 unauthorized". 

### ISSUE THREAD

**Issue by illuminated** [suer/omniauth-redmine#4]
I'm getting a 500 error when the callback url is being opened.

I have succesfully installed the redmine_oauth_provider on Redmine and created a new app.
I have then added the omniauth-redmine gem to GitLab, configured the config/gitlab.yml:
```
  omniauth:
    # Allow login via Twitter, Google, etc. using OmniAuth providers
    enabled: true

    # CAUTION!
    # This allows users to login without having a user account first (default: false).
    # User accounts will be created automatically when authentication was successful.
    allow_single_sign_on: false
    # Locks down those users until they have been cleared by the admin (default: true).
    block_auto_created_users: false
    # Look up new users in LDAP servers. If a match is found (same uid), automatically
    # link the omniauth identity with the LDAP account. (default: false)
    auto_link_ldap_user: false
    providers:
       - { name: 'redmine',
           consumer_key: 'nyuHGr.................X1x',
           consumer_secret: 'zn3z....................Cun6',
           redmine_base_url: 'http://my.base_url.com/' }
```
configured the initializer/omniauth.rb by adding on top:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :redmine, "nyuH.........X1x", "zn3z.........Cun6", :redmine_base_url => "http://my.redmine_base.com/"
end
```

On the Gitlab's Sign In page I get the "Redmine" button. Clicking it puts me on the authorize page, I click on "Allow", get back to Gitlab and the 500 error page is rendered.

This is the error log on GitLab:
```
Started GET "/users/sign_in" for my.IP.address at 2016-01-17 03:13:07 +0100
Processing by SessionsController#new as HTML
Completed 200 OK in 293ms (Views: 66.5ms | ActiveRecord: 7.9ms)
Started POST "/users/auth/redmine" for my.IP.address at 2016-01-17 03:13:12 +0100
Processing by OmniAuth::RequestForgeryProtection::Controller#index as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/users/auth/redmine/callback?oauth_token=[FILTERED]&oauth_verifier=EAYsTb6jJsU8SZMpUsab" for my.IP.address at 2016-01-17 03:13:14 +0100

NoMethodError (undefined method `end_with?' for nil:NilClass):
  omniauth-redmine (0.0.2) lib/omniauth/strategies/redmine.rb:32:in `redmine_base_url'
  omniauth-redmine (0.0.2) lib/omniauth/strategies/redmine.rb:9:in `consumer'
  omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:47:in `callback_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:362:in `callback_phase'
  omniauth-oauth (1.1.0) lib/omniauth/strategies/oauth.rb:57:in `callback_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
  rack-attack (4.3.1) lib/rack/attack.rb:106:in `call'
  warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.4) lib/warden/manager.rb:34:in `catch'
  warden (1.2.4) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.4) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.4) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.2.1) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  railties (4.2.4) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.4) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `each'
  rack (1.6.4) lib/rack/urlmap.rb:50:in `call'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn-worker-killer (0.4.4) lib/unicorn/worker_killer.rb:52:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn_rails:209:in `<top (required)>'
  /usr/local/bin/unicorn_rails:23:in `load'
  /usr/local/bin/unicorn_rails:23:in `<main>'
```

**Comment by illuminated** [comment]
I have managed to get rid of the rails error, but still cannot login.

I have changed the gitlab.yml config to:
```
       - { name: 'redmine',
           'consumer key': 'nyuHGrUuMEjN6pNwiu46M0zK9vIlgTRDqaAANX1x',
           'consumer secret': 'zn3zQXD4MZFzsTMMfXZH3T0PLjDAdbt4VX6OCun6',
           args: {
                   redmine_base_url: 'http://work.smallideafactory.com/' } }
```
I was playing a lot with the gitlab.yml and the only thing that made the rails error gone was putting the redmine_base_url within "args".

And the error now is:
```
Started POST "/users/auth/redmine" for my.IP.address at 2016-01-17 10:11:38 +0100
Processing by OmniAuth::RequestForgeryProtection::Controller#index as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]"}
Completed 200 OK in 1ms (ActiveRecord: 0.0ms)
Started GET "/users/auth/redmine/callback?oauth_token=[FILTERED]&oauth_verifier=MK1CvGAbPPa0afLUDSmG" for my.IP.address at 2016-01-17 10:11:41 +0100
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"oauth_token"=>"[FILTERED]", "oauth_verifier"=>"MK1CvGAbPPa0afLUDSmG"}
Redirected to http://gitlab.smallideafactory.com/users/sign_in
Completed 302 Found in 166ms (ActiveRecord: 5.8ms)
Started GET "/users/sign_in" for my.IP.address at 2016-01-17 10:11:41 +0100
Processing by SessionsController#new as HTML
Completed 200 OK in 318ms (Views: 67.1ms | ActiveRecord: 10.2ms)
```

**Comment by illuminated** [comment]
Redmine error log is also throwing some errors:

```
Started POST "/oauth/authorize" for MY.IP.ADDRESS at 2016-01-17 10:26:38 +0100
Processing by OauthController#authorize as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"M7WVAravT9hgznJqOJiVpUmQI9+52axZzhku4ENG6C4FBVl5AfbbxY6Sz6dGqsD4uqxZcAh5uJRaTkk+iCLgfA==", "oauth_token"=>"VckW3jzzeU3i5nlyT1Z4DguSwYg1Bpxm8h6FK5W$
  Current user: user@mydomain.com (id=5)
Redirected to http://gitlab.mydomain.com/users/auth/redmine/callback?oauth_token=VckW3jzzeU3i5nlyT1Z4DguSwYg1Bpxm8h6FK5WV&oauth_verifier=X9Enio85SZlWSDER4E7j
Completed 302 Found in 16ms (ActiveRecord: 3.9ms)
Started POST "/oauth/access_token" for 127.0.0.1 at 2016-01-17 10:26:38 +0100
Processing by OauthController#access_token as */*
  Current user: anonymous
  Rendered text template (0.1ms)
Completed 200 OK in 13ms (Views: 0.6ms | ActiveRecord: 2.7ms)
Started GET "/oauth/user_info.json" for 127.0.0.1 at 2016-01-17 10:26:38 +0100
Processing by OauthController#user_info as JSON
  Current user: anonymous
Completed 200 OK in 15ms (Views: 0.6ms | ActiveRecord: 3.6ms)
Started POST "/oauth/access_token" for 127.0.0.1 at 2016-01-17 10:26:38 +0100
Processing by OauthController#access_token as */*
  Current user: anonymous
  Rendered text template (0.0ms)
Filter chain halted as #<OAuth::Controllers::ApplicationControllerMethods::Filter:0x007fb8afa42b20 @options={:interactive=>false, :strategies=>:oauth10_request_token}, @strategies=[:oauth10_request$
Completed 401 Unauthorized in 4ms (Views: 0.5ms | ActiveRecord: 0.8ms)
Started GET "/time_loggers/render_menu?_=1453020516561" for MY.IP.ADDRESS at 2016-01-17 10:26:46 +0100
Processing by TimeLoggersController#render_menu as */*
  Parameters: {"_"=>"1453020516561"}
  Current user: user@mydomain.com (id=5)
  Rendered plugins/time_logger/app/views/time_loggers/_embed_menu.html.erb (3.7ms)
Completed 200 OK in 13ms (Views: 3.5ms | ActiveRecord: 3.2ms)
Started GET "/oauth_clients/1" for MY.IP.ADDRESS at 2016-01-17 10:26:50 +0100
Processing by OauthClientsController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: user@mydomain.com (id=5)
  Rendered plugins/redmine_oauth_provider/app/views/oauth_clients/show.html.erb within layouts/base (1.3ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_head.html.erb (0.2ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_header.erb (8.9ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_sidebar.html.erb (0.2ms)
  Rendered plugins/progressive_projects_list/app/views/application/_progressive_recent_projects.html.erb (1.6ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_content.erb (0.2ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_tooltip.html.erb (0.7ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom.html.erb (0.5ms)
  Rendered plugins/quick_view/app/views/hooks/_quick_view_base_bottom_worktime_ext.html.erb (0.2ms)
  Rendered plugins/time_logger/app/views/time_loggers/_embed_menu.html.erb (3.5ms)
  Rendered plugins/time_logger/app/views/time_loggers/_update_menu.html.erb (4.2ms)
  Rendered plugins/redmine_tweaks/app/views/application/_global_footer.erb (0.2ms)
Completed 200 OK in 49ms (Views: 36.6ms | ActiveRecord: 5.8ms)
```

These lines seem odd to me:
```
Processing by OauthController#access_token as */*
  Current user: anonymous
```

**Comment by illuminated** [comment]
Found the error and solved the problem. Instead of configuring initializer/omniauth.rb, I shoud have configured the initializer/devise.rb.
I have put a wiki page [here](https://github.com/suer/omniauth-redmine/wiki/Working-Gitlab-Redmine-integration) explaining the steps, as well as on the [GitLab's wiki](https://github.com/gitlabhq/gitlab-public-wiki/wiki/Custom-omniauth-provider-configurations#working-redmine-integration).

**Comment by suer** [comment]
I did not know ```Redmine Integration``` in the Gitlab's wiki page.
Thank you for writing a document about integration with Gitlab.
